### ISSUE TITLE
Can we save pdf directly without showing the print preview screen

### ISSUE THREAD

**Issue by Deepak2985** [gharibi/JsObjExporter#11]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gharibi** [comment]
Hey @Deepak2985. Interesting use-case. Short answer is at the moment the API doesn't support this, however I think it is a good idea to implement it.

Just to underestand your use-case more, do you want to have your own dialog to ask the user where to save the pdf?

In order to fire the print function, we are using `contentWindow` property which returns the Window object of an `HTMLIFrameElement`. By this Window object, we can theoritically to access the iframe's document and its internal DOM.

So, in order to implement this functionality, we should initially hide the `contentWindow` property and implement a callback or promise.

**Comment by Deepak2985** [comment]
@gharibi First of all thank you for such a fast response. I really appreciate it. The use-case is I have a button in my application. On click of the button, I want to export a JSON array as pdf. The pdf should get downloaded. I don't want a print preview screen just a pdf file downloaded.

**Comment by gharibi** [comment]
Thanks @Deepak2985. Indeed it could be a typical use-case. I will look deeper into it and will let you know how it goes.

**Comment by Deepak2985** [comment]
Thank you @gharibi. I will be waiting for your response. 🙂

**Comment by gharibi** [comment]
So, I'm afraid I don't have good news. Browsers tend to keep a consistent user experience, therefore they don't allow the runtime to control their behaviour. In other words, there is no way to hide the print preview page by javascript.

Also as far as I could dig out from Chrome runtime documentation as an example, the print preview page is actually generating a `base64` data string which then the user can directly download.

Given the information above, the only thing I could offer is to support `base64` printing. In this case, you can pass your data url (which you should generate from your server) to the API. This would allow you to bypass the print preview.

**Comment by gharibi** [comment]
I proceed to close this issue, however if you have any comments about it, you can come back and open it at any time.
